name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Test
        run: |
          echo $API
        env: 
          API: ${{ secrets.API_IQAIR }}
        

name: Secrets
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$API" == "acaad8b2-e27f-44f9-ba13-9c2e6425d0ce" ]
          then
            echo "Got secret"
          fi
        env: 
          API: ${{ secrets.API_IQAIR }}